=== zhaoccx/JavaCode/ItCast_001_XML/dtd/books4.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT books (book+)>
<!ELEMENT book (title?,price*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT price EMPTY>


<!ATTLIST book 
	id ID #REQUIRED
	pId IDREF #IMPLIED
	city CDATA #FIXED "北京"
	lang (EN|CN|JP|TW) "CN"
>

=== zhaoccx/JavaCode/ItCast_001_XML/dtd/books4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "books4.dtd">
<books>
	<book id="b001">
		<title></title>
		<price ></price>		
		<price></price>		
	</book>
	<book id="b002" pId="b001" lang="EN">
		<title></title>
		<price ></price>		
		<price></price>		
	</book>

</books>
